
CREATE TABLE CLIENTES 
(
  IDCLIENTE NUMBER NOT NULL 
, NOMBRECLIENTE VARCHAR2(50) 
, FECHACREACION DATE 
, ESTADO CHAR(1) 
, CONSTRAINT CLIENTES_PK PRIMARY KEY 
  (
    IDCLIENTE 
  )
  ENABLE 
);

CREATE TABLE PRODUCTOS 
(
  IDPRODUCTO NUMBER NOT NULL 
, NOMBREPRODUCTO VARCHAR2(50) 
, FECHACREACION DATE 
, ESTADO CHAR(1) 
, CONSTRAINT PRODUCTOS_PK PRIMARY KEY 
  (
    IDPRODUCTO 
  )
  ENABLE 
);

CREATE TABLE CLIENTE_PRODUCTO 
(
  ID NUMBER NOT NULL 
, IDCLIENTE NUMBER 
, IDPRODUCTO NUMBER 
, CONSTRAINT CLIENTE_PRODUCTO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT CLIENTE_PRODUCTO_FK1 FOREIGN KEY
(
  IDCLIENTE 
)
REFERENCES CLIENTES
(
  IDCLIENTE 
)
ENABLE;

ALTER TABLE CLIENTE_PRODUCTO
ADD CONSTRAINT CLIENTE_PRODUCTO_FK2 FOREIGN KEY
(
  IDPRODUCTO 
)
REFERENCES PRODUCTOS
(
  IDPRODUCTO 
)
ENABLE;